Runtime/GraphicsCaptureFrameSource.cpp

对_newFrameArrived的操作应该放在CRITICAL_SECTION中，Update和_OnFrameArrived为不同线程，此处的赋值会破坏CRITICAL_SECTION，导致_OnFrameArrived函数中LeaveCriticalSection异常

修复GraphicsCapture CRITICAL_SECTION异常

---

.github/workflows/wiki.yml
ci/wiki.sh
docs/Built-in effects.md

SwiftDocOrg/github-wiki-publish-action 无法处理文件名中的空格，这个 pr 拷贝了它的代码并修复这个错误。

修复自动发布 wiki

---

src/Magpie.App/ContentDialogHelper.cpp
src/Magpie.App/LocalizationService.cpp
src/Magpie.App/LocalizationService.h
src/Magpie.App/MainPage.cpp
src/Magpie.App/ShortcutControl.cpp
src/Magpie.App/ShortcutControl.h
src/Magpie.App/ShortcutControl.xaml

修复 https://github.com/Blinue/Magpie/pull/592#issuecomment-1539559818 发现的错误。
控件根据 Language 属性选择合适的字体，但我没找到这个机制的文档。这是摇摇欲坠的 XAML Islands 的又一个补丁。
对比：[日语](https://imgsli.com/MTc3NTI3) [繁体中文](https://imgsli.com/MTc3NTI4)

fix: 根据显示语言选择字体

---

src/Magpie.Core/Magpie.Core.vcxproj
src/Magpie.Core/Magpie.Core.vcxproj.filters
src/Magpie.Core/OverlayDrawer.cpp
src/Magpie.Core/OverlayDrawer.h
src/Magpie.Core/Renderer.cpp

移除这个字体文件可使软件体积减小 20%，改为使用 Segoe UI 族（Win10 为 Segoe UI，Win11 为 Segoe UI Variable）。Segoe UI 的数字字符不是等宽的，为了提升观感，构造字体时应对数字特殊处理。
效果：
现在需要三种字体：
1. 用于绘制 UI 的 Segoe UI，对于简/繁中文和日语需要加载额外的字体（这将在下一个 PR 中和本地化一起实现）
2. 用于绘制 UI 中数字的字体，以 Segoe UI 为蓝本，数字字符是等宽的
3. 用于绘制 FPS 的字体，它的数字也应是等宽的

移除 NotoSansSC-Regular.otf

---

Directory.Build.props
src/Magpie.App/CaptionButtonsControl.cpp
src/Magpie.App/CaptionButtonsControl.h
src/Magpie.App/CaptionButtonsControl.idl
src/Magpie.App/CaptionButtonsControl.xaml
src/Magpie.App/MainPage.cpp
src/Magpie.App/MainPage.xaml
src/Magpie.App/TitlebarControl.cpp
src/Magpie.App/TitlebarControl.h
src/Magpie.App/TitlebarControl.idl
src/Magpie.App/TitlebarControl.xaml
src/Magpie/MainWindow.cpp
src/Magpie/XamlWindow.h
src/Solution.props

https://github.com/Blinue/Magpie/assets/34770031/9dfb4428-5545-4bca-a697-d50467f15745
有些 UWP 窗口会使标题变灰，有些不会。标题按钮的样式都是统一的。

窗口失去焦点时使标题和标题栏按钮变灰

---

src/Magpie.App/AppSettings.cpp
src/Magpie.App/AppSettings.h
src/Magpie.App/MagService.cpp
src/Magpie.App/Resources.language-en-US.resw
src/Magpie.App/Resources.language-zh-Hans.resw
src/Magpie.App/SettingsPage.xaml
src/Magpie.App/SettingsViewModel.cpp
src/Magpie.App/SettingsViewModel.h
src/Magpie.App/SettingsViewModel.idl
src/Magpie.Core/MagApp.cpp
src/Magpie.Core/MagOptions.h
src/Magpie.Core/Renderer.cpp

v0.10 禁止缩放这种窗口，我们添加一个选项带回这个功能，下面是一些使用场景
* 作为滤镜使用
* 自定义裁剪
* 多屏幕
**实测支持独占全屏。**
Closes #559

允许缩放最大化或全屏的窗口

---

src/Magpie.App/AppSettings.cpp
src/Magpie.App/FileDialogHelper.cpp
src/Magpie.App/FileDialogHelper.h
src/Magpie.App/Magpie.App.vcxproj
src/Magpie.App/Magpie.App.vcxproj.filters
src/Magpie.App/Profile.h
src/Magpie.App/ProfilePage.xaml
src/Magpie.App/ProfileViewModel.cpp
src/Magpie.App/ProfileViewModel.h
src/Magpie.App/ProfileViewModel.idl
src/Magpie.App/Resources.language-en-US.resw
src/Magpie.App/Resources.language-zh-Hans.resw
src/Magpie.App/ScalingConfigurationViewModel.cpp

某些游戏需要通过“启动器”启动，因此用户需要自定义启动器的路径。
此选项不适用于打包应用。
Closes #609

允许更改用于启动的可执行文件

---

src/Magpie/MainWindow.cpp

最大化时向下还原按钮的文字提示为“最大化”，Win11 中关闭贴靠布局也会看到这个错误。
文字提示是标题栏窗口弹出的，这个窗口不会改变状态。我们不能真的将它最大化了，但可以通过设置 WS_MAXIMIZE 样式欺骗 OS。

修复向下还原按钮的文字提示

---

src/Magpie/app.manifest

Windows 11 23H2 于 2023 年 10 月 31 日发布，版本号 22631。对于每一个新发布的正式版本，我们应更新 manifest 声明对它的支持，这可以让 OS 启用某些新功能。

feat: 适配 Win11 23H2

---

src/Magpie/MainWindow.cpp
src/Magpie/MainWindow.h

fix #661 
修正前：
修正后：
这是大部分自定义标题栏的应用都有的问题，但似乎无人关心。经过了很长时间，我终于找到了解决方案。
在贴靠布局弹窗显示之前，窗口会收到 WM_GETOBJECT 消息，因此我猜测 OS 使用 UI Automation 来获取标题栏高度，如果不可用就假设和原生窗口相同。UI Automation 我并不了解，但我们可以变通一下：Win32 控件有默认的 UI Automation 机制，我们只需将一个原生按钮摆放在这里，OS 便会将它当作最大化/还原按钮，从而将贴靠布局弹窗显示在正确的位置。
因此我们有了一个不可见、禁用状态的原生按钮控件，它的高度和标题栏按钮相同，唯一的作用便是修正贴靠布局弹窗的位置。

修正贴靠布局弹窗位置

---

Magpie.sln
publish.py
src/Common.Post.props
src/HybridCRT.props
src/Magpie.App/Magpie.App.vcxproj
src/Magpie.App/ProfilePage.xaml
src/Magpie.App/packages.config
src/Magpie/Magpie.vcxproj
src/Magpie/packages.config
src/WinUI.props
src/extract_winui_runtime.py
src/fix_resfiles.py

根据[文档](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/xaml-islands#supported-only-with-workarounds)，XAML Islands 在非打包应用中只能使用预发行版本的 WinUI。WinUI 已经很久没有发布过预发行版本了，为了获得最新的修复，应想办法使用正式版本。
直接升级 WinUI 包会导致编译错误，因为正式版和预发行版包的结构不同：预发行版包含 dll、winmd 和 pri，而正式版只包含 AppX。这个 PR 中添加了一些编译脚本，当引用正式版 WinUI 时，提取出 AppX 包中的 dll 和 winmd 并添加对它们的引用。另外还有一些（很多） hack 来防止编译错误。
WinUI 从 2.8.2-prerelease 升级到 2.8.6。

使用正式版 WinUI

---

src/Magpie.App/NewProfileViewModel.cpp

判断窗口是否可见比想象中复杂，我们应查看父窗口链和所有者链，只要其中有一个窗口是隐藏的，该窗口也是隐藏的。[IsWindowVisible](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindowvisible) 不检查所有者窗口，结果不准确。

修复新配置候选窗口有时会包含不可见的窗口的问题

---

src/Magpie/MainWindow.cpp
src/Magpie/MainWindow.h
src/Magpie/XamlApp.cpp
src/Magpie/XamlApp.h

fix #706
创建主窗口前检查起始位置是否存在屏幕。具体而言检查两个点：
1. 窗口中心点：确保大部分窗口内容可见
2. 上边框中心点：确保大部分标题栏可见
如果窗口不在任何屏幕上，则由 OS 决定启动位置。

防止窗口启动时不在可见区域

---

src/Magpie.App/ScalingConfigurationPage.xaml
src/Magpie.App/SettingsCard.cpp
src/Magpie.App/SettingsExpander.cpp
src/Magpie.App/SettingsExpander.h
src/Magpie.App/SettingsExpander.idl
src/Magpie.App/SettingsExpander.xaml
src/Magpie.App/ShortcutDialog.xaml

1. SettingsExpander.Items 的容器从 ListView 换成更轻量的 ItemsControl，这也意味着不支持拖拽排序了，ScalingConfigurationPage 改为使用独立的 ListView。
2. 删除 SettingsExpanderItemStyleSelector，改为直接从资源中检索样式。
3. 删除 SettingsExpander 的 ItemContainerStyleSelector 和 CanReorderItems 属性。
4. ScalingConfigurationPage 的两个 ListView 改为 ItemsControl。
5. 优化 ShortcutDialog 和 ScalingConfigurationPage 的键盘导航。

优化 SettingsExpander 的性能

---

src/Magpie.App/SettingsCard.cpp

不知为何 SettingsCard 的 Header 或 Description 属性为空字符串（`box_value(L"")`）会导致崩溃，这个 PR 添加了额外的检查。

修复空缩放模式导致的崩溃

---

src/Magpie.Core/MagApp.cpp

Close #808
这个错误是 #502 引入的，为了被 Wallpaper Engine 检测到而使用 
```
ShowWindow(_hwndHost, SW_SHOWMAXIMIZED);
```
显示缩放窗口，但 Windows 中最大化窗口是不能跨越多个屏幕的。
修复方式是只有在单个屏幕上缩放才最大化，跨越多个屏幕时则使用无边框全屏。Wallpaper Engine 检测不到无边框全屏窗口，但这是它自己的错误，我们没必要牺牲太多。

修复缩放窗口不能跨越多个屏幕的错误

---

src/Magpie.Core/EffectCompiler.cpp

This pull request should fix saving of intermediate effect source files when the effect file is stored in a subdirectory.
Without this patch enabling "Save source code when parsing effects" results in an error like this `|error|Win32Utils.cpp:bool __cdecl Win32Utils::WriteFile(const wchar_t *,const void *,unsigned __int64) noexcept|打开文件 sources\**\*.hlsl 失败` in the log when the effect is not stored in the root of the `Effects` directory tree.

Fix generation of effect source files in subdirectories

---

src/Magpie.Core/DeviceResources.cpp

Close #838 
Magpie 需要显卡支持 DirectX 功能级别 11，如果没有可用的显卡，应回落到使用 CPU 渲染，即 Basic Render Driver Adapter（WARP）。这个 PR 修复因为忘记调用 _TryCreateD3DDevice 导致的回落失败。

修复找不到可用显卡时回落到 WARP 失败的问题

---

src/Magpie.Core/OverlayDrawer.cpp

Close #649
3D 游戏模式下打开叠加层时光标由 ImGui 渲染，因此字体纹理中含有光标数据，和非 3D 游戏模式中的字体纹理不兼容，这是导致打开叠加层时崩溃的原因。#643 重写了架构，光标不再交给 ImGui 渲染，因此不存在这个 bug。
这个修复针对 v0.10，只是简单的在 3D 游戏模式下禁用字体缓存。

防止 3D 游戏模式下打开叠加层可能导致的崩溃

---

src/Magpie.Core/CursorDrawer.cpp
src/Magpie.Core/CursorDrawer.h
src/Magpie.Core/shaders/MaskedCursorPS.hlsl
src/Magpie.Core/shaders/MonochromeCursorPS.hlsl

Close #853 
Desktop Duplication 的文档记录了不同类型的光标的工作方式：[DXGI_OUTDUPL_POINTER_SHAPE_TYPE](https://learn.microsoft.com/en-us/windows/win32/api/dxgi1_2/ne-dxgi1_2-dxgi_outdupl_pointer_shape_type)
单色光标和彩色掩码光标均涉及到掩码操作，双线性插值对它们没有意义，但有些老游戏使用这两种光标却不使用掩码。在当前实现下，即使使用双线性插值，这些光标依然有锐利的边缘，这是因为从不应用掩码状态到应用掩码/透明状态是突变的。
双线性插值下的单色光标：
此 PR：
此 PR 将兼容的单色光标和彩色掩码光标转换为彩色光标。彩色光标的优势在于：
1. 渲染更快，因为可以使用图形管线的混合状态来实现透明度，避免了复制原始纹理。
2. 可以使用预乘 Alpha 优化线性插值结果，使得透明像素和非透明像素之间有着平滑的过渡。
对于使用了掩码的光标不支持双线性插值，它们将始终使用最近邻插值。这样的光标非常少，且双线性插值对它们没有意义，比如最常见的有着反色区域的 I 形光标。

优化双线性插值下单色光标和彩色掩码光标的渲染效果

---

src/Magpie.App/ScalingService.cpp
src/Magpie.App/ScalingService.h
src/Magpie.Core/ScalingRuntime.cpp
src/Magpie.Core/ScalingRuntime.h
src/Magpie.Core/ScalingWindow.cpp

Close #826 
不再使用 _hwndSrc 作为是否正在缩放的标志，而是使用专用的 _state 成员，有三种状态：
```mermaid
flowchart LR
Idle--Start()-->Initializing
Initializing--缩放成功-->Scaling
Initializing--缩放失败-->Idle
Scaling--缩放结束-->Idle
```
对于用户来说，Initializing 和 Scaling 为正在缩放状态。当正在缩放时，按下热键可停止缩放，反之则执行缩放。
还修复了一个退出时死锁的 bug。

简化 ScalingRuntime 状态

---

src/Magpie.Core/CursorManager.cpp
src/Magpie.Core/ScalingWindow.cpp
src/Magpie.Core/ScalingWindow.h

在调试过程中，我发现 SetCursorPos 无法可靠移动光标，虽然调用之后立刻查询光标位置没有问题，但经过一段时间后再次查询会发现光标位置又回到了设置之前。我怀疑这是因为 OS 异步处理硬件输入队列，SetCursorPos 时队列中仍有旧事件尚未处理。
现在使用 SendInput 将移动光标的事件插入输入队列，然后等待系统处理到该事件，避免了并发问题。如果设置不成功则多次尝试。这里旨在尽最大努力，因为这是 OS 的 bug，我怀疑是否有完美的解决方案。
经过测试，新方案似乎解决了问题，我没有再遇到光标跳跃的问题。

修复光标移动到叠加层或其他窗口时有时会跳跃的问题

---

src/Magpie.App/ScalingService.cpp
src/Magpie.App/ScalingService.h
src/Shared/Win32Utils.cpp
src/Shared/Win32Utils.h

由于 UIPI (用户界面特权隔离)，当高完整性级别 (integrity level) 的窗口位于前台时，很多调用会失败，比如设置光标位置、禁用圆角等。虽然也可以在这种情况下允许功能降级，但可能造成困惑 #831。出于一致性考虑，禁止缩放完整性级别更高的窗口。

禁止缩放完整性级别更高的窗口

---

src/Magpie.Core/FrameSourceBase.cpp
src/Shared/Win32Utils.cpp
src/Shared/Win32Utils.h

Close #876
有些全屏的窗口实际上是“最大化”的，比如 Magpie 缩放窗口为了和 Wallpaper Engine 兼容 #812 就使用了这个技术。因此现在情况比较复杂了：
1. 原生最大化窗口需要裁剪到屏幕工作区，由于最大化窗口的实现机制，窗口有一部分位于工作区外，在 Win11 中甚至下边框也是存在的。
2. 全屏最大化窗口通常会覆盖任务栏，因此应裁剪到屏幕边界，而不是工作区。Windows 不会阻止全屏最大化窗口跨越多个屏幕，但依然只会在一个屏幕上渲染，因此可以认为全屏最大化窗口和原生最大化窗口一样不能跨越多个屏幕。
以是否绘制了原生边框区分这两种窗口。

修复对全屏窗口的支持

---

src/Magpie.App/ScalingConfigurationPage.xaml
src/Magpie.App/ScalingConfigurationViewModel.cpp
src/Magpie.App/ScalingConfigurationViewModel.h
src/Magpie.App/ScalingConfigurationViewModel.idl
src/Magpie.App/SettingsExpander.Resource.xaml

Close #878 
添加/删除项目的动画会导致 bug，除了 #878 的动画 bug，还会导致缩放模式在错误的时机折叠，我没有调查具体原因。除了这两个 bug，还有其他原因使我决定删除这个动画：
1. 动画过于冗长，而且无法设置时长。删除这个动画能使 UI 响应更快
2. 和整体风格保持一致，导航栏以及其他页面都没有添加/删除动画
添加了其他动画让 UI 不那么朴素。

缩放配置页面不再展示添加/删除动画

---

src/Magpie.App/ScalingConfigurationPage.xaml
src/Magpie.App/SimpleStackPanel.cpp

看起来 x:bind 是在 Measure 时执行绑定，因此即使子项是隐藏的，也应调用 Measure。

修复 SimpleStackPanel 的子项绑定有时不起作用的问题

---

src/Magpie.App/ScalingConfigurationPage.xaml

这个 bug 一旦连接调试器就不会出现，让我想起了 https://github.com/Blinue/Magpie/pull/771#pullrequestreview-1775229194 ，但大概没有联系。玄学错误就用玄学来修复，我发现不自定义 ListView.ItemsPanel，即使用默认的 ItemsStackPanel 时就没有这个问题。具体原因仍是个谜。

修复缩放配置页面的设置项错误折叠的问题

---

README.md
README_ZH.md
docs/Interact with Magpie programally.md
docs/以编程方式与 Magpie 交互.md
src/Magpie.Core/ScalingWindow.cpp
src/Magpie.Core/ScalingWindow.h
src/Magpie/MainWindow.cpp
src/Magpie/XamlApp.cpp
src/Magpie/XamlWindow.h
src/Shared/CommonSharedConstants.h
src/Shared/Utils.h

Close #447 
我创建了 [MagpieWatcher](https://github.com/Blinue/MagpieWatcher) 来演示这些机制。
监听 MagpieScalingChanged 消息。
```c++
UINT WM_MAGPIE_SCALINGCHANGED = RegisterWindowMessage(L"MagpieScalingChanged");
```
`wParam` 为事件 ID，对于不同的事件 `lParam` 有不同的含义。目前支持两个事件：
* 0: 缩放已结束。不使用 `lParam`。
* 1: 缩放已开始。`lParam` 为缩放窗口句柄。
如果你的进程完整性级别 (Integration level) 比 Magpie 更高，由于用户界面特权隔离 (UIPI)，你将无法收到 Magpie 广播的消息。这种情况下请调用 ChangeWindowMessageFilter 允许接收 MagpieScalingChanged 消息。
```c++
ChangeWindowMessageFilter(WM_MAGPIE_SCALINGCHANGED, MSGFLT_ADD);
```
你可以监听 MagpieScalingChanged 消息来获取缩放窗口句柄，也可以查找类名为`Window_Magpie_967EB565-6F73-4E94-AE53-00CC42592A22`的窗口以在缩放中途获取该句柄。Magpie 将确保此类名不会改变，且不会同时存在多个缩放窗口。
```c++
HWND hwndScaling = FindWindow(L"Window_Magpie_967EB565-6F73-4E94-AE53-00CC42592A22", nullptr);
``` …

添加和其他程序交互的机制

---

src/Magpie.App/ProfileService.cpp
src/Magpie.App/ProfileService.h
src/Shared/StrUtils.h

Close #904 
TeknoParrot 中的 BudgieLoader.exe 用于运行 Linux 游戏，每次启动窗口类名都会改变，格式为 XWindow_{一串数字}。这个 PR 还优化了解析窗口类名的性能。

适配 TeknoParrot 的窗口类名

---

src/Magpie.App/HomePage.cpp
src/Magpie.App/HomePage.h
src/Magpie.App/HomePage.xaml
src/Magpie.App/PageFrame.cpp
src/Magpie.App/PageFrame.idl
src/Magpie.App/PageFrame.xaml
src/Magpie.App/Resources.language-en-US.resw
src/Magpie.App/Resources.language-zh-Hans.resw

这个选项和 D3D9 不兼容，会使很多旧游戏出错。见 #588

为模拟独占全屏选项添加警告

---

src/Magpie.Core/ExclModeHelper.cpp
src/Magpie.Core/ScalingWindow.cpp
src/Updater/main.cpp

Close #937
Close #928
这个 bug 是 #894 引入的。wil::unique_mutex_nothrow 在析构时不会自动释放，虽然我开发 #894 的过程中注意到了，但一些旧代码忘记调整了。

修复忘记释放某些 mutex

---

docs/Interact with Magpie programally.md
docs/以编程方式与 Magpie 交互.md
src/Magpie.Core/ScalingWindow.cpp
src/Magpie.Core/ScalingWindow.h

SetProp 文档要求窗口被销毁前清理所有属性，这个 PR 添加了清理的代码。实际上这不是必须的，见 https://devblogs.microsoft.com/oldnewthing/20231030-00/?p=108939

fix: 缩放窗口销毁前清理属性，以及更新文档说明清理窗口属性

---

src/Magpie.App/IconHelper.cpp

虽然很少见，但确实存在可执行文件的图标是彩色掩码图标的情况。注意彩色掩码图标可能无法无损转换到常规图标，由于 UI 图像不支持应用掩码，如果遇到不支持的情况会直接忽略掩码，而渲染光标时我们使用着色器来正确处理。
当前：
此 PR：
依然不支持单色图标，难以想象可执行文件的图标会是单色图标。如果真的存在，以来再来支持。

游戏图标支持彩色掩码图标

---

src/Magpie.App/TouchHelper.cpp
src/Magpie.Core/ScalingWindow.cpp
src/Magpie/XamlApp.cpp

Close #992 
出于未知原因，启用了“以管理者身份运行该程序”兼容性选项的程序无法获得 UIAccess 权限。这个 PR 委托 explorer 启动 TouchHelper，从而绕过这个限制。

fix: 修复启用“以管理者身份运行该程序”兼容性选项时 TouchHelper 无法获得 UIAccess 权限的问题

---

.all-contributorsrc
README.md
README_ZH.md
docs/Built-in effects.md
docs/内置效果介绍.md
src/Effects/CuNNy/CuNNy-16x16C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-16x16C-NVL.hlsl
src/Effects/CuNNy/CuNNy-2x4C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-2x4C-NVL.hlsl
src/Effects/CuNNy/CuNNy-3x4C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-3x4C-NVL.hlsl
src/Effects/CuNNy/CuNNy-4x16C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-4x16C-NVL.hlsl
src/Effects/CuNNy/CuNNy-4x4C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-4x4C-NVL.hlsl
src/Effects/CuNNy/CuNNy-4x8C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-4x8C-NVL.hlsl
src/Effects/CuNNy/CuNNy-6x8C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-6x8C-NVL.hlsl
src/Effects/CuNNy/CuNNy-8x16C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-8x16C-NVL.hlsl
src/Effects/CuNNy/CuNNy-8x4C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-8x4C-NVL.hlsl
src/Effects/CuNNy/CuNNy-8x8C-NVL-DN.hlsl
src/Effects/CuNNy/CuNNy-8x8C-NVL.hlsl

https://github.com/cunnyplapper/CuNNy 链接现已无法访问，替换为 https://github.com/funnyplanter/CuNNy
此PR只替换了上面给出的链接。`.all-contributorsrc` 里单独出现了 cunnyplapper，目前暂未替换，不确定要不要换。

修复CuNNy的死链

---

src/Magpie/Profile.h

Close #1064
不复制自动缩放选项是故意的，因为这个选项和缩放配置无关，但确实不符合直觉。

复制配置文件时复制自动缩放选项

---

src/Magpie/Magpie.vcxproj
src/Magpie/Magpie.vcxproj.filters
src/Magpie/MainWindow.cpp
src/Magpie/MainWindow.h
src/Magpie/RootPage.cpp
src/Magpie/SmoothResizeHelper.cpp
src/Magpie/SmoothResizeHelper.h
src/Magpie/TitlebarControl.cpp
src/Magpie/TitlebarControl.h
src/Magpie/TitlebarControl.xaml
src/Magpie/XamlWindow.h

XAML Islands 一直以来存在不能流畅调整大小的问题，https://github.com/microsoft/microsoft-ui-xaml/issues/759 已经存在五年多，最新的 WinUI 3 仍没有修复。现在 apkipa 找到了办法 https://github.com/Blinue/Magpie/pull/1071#issuecomment-2710669084 ，效果相当好。 
（说个题外话，这个功能的官方名称似乎是 Smooth Window Resize，[有个文档](https://learn.microsoft.com/en-us/uwp/api/windows.ui.windowmanagement.appwindow?view=winrt-26100#limitations)使用了这个名词。）
1. 初始化 XAML Islands 后调用未记录的函数 EnableResizeLayoutSynchronization。
2. 处理 WM_SIZE 时调用 IFrameworkApplicationPrivate::SetSynchronizationWindow。IFrameworkApplicationPrivate 是一个内部 COM 接口，可以通过 Application 检索得到。
鉴于微软有过随意更改内部接口 ABI 的历史，使用 IFrameworkApplicationPrivate 可能会造成崩溃。我已在多个 Windows 版本中测试（下至 Win10 v1903，上至 Win11 24H2），这个接口一直可用。我猜出于兼容性考虑微软已经把它冻结了，这个接口很早就有软件在用。
Win10 存在一个 …

修复主窗口调整大小时边缘闪烁

---

src/Magpie.Core/include/CommonSharedConstants.h
src/Magpie/TouchHelper.cpp
src/TouchHelper/main.cpp

部分修复 #1135。“已有实例”弹窗在设计中永远不会出现，如果检测到 TouchHelper.exe 正在运行，Magpie 不会再次启动 TouchHelper，但这个机制无法防止第一次启动 TouchHelper 尚未完成就再次尝试启动。这个 PR 删除了这个弹窗。
提高了 TouchHelper 的版本号，缩放前可能会请求管理员权限。

避免短时间内多次启动 TouchHelper 时弹出消息

---

src/Magpie.Core/Magpie.Core.vcxproj.filters
src/Magpie/ToastPage.cpp
src/Magpie/XamlHelper.cpp
src/Magpie/XamlHelper.h
src/TouchHelper/TouchHelper.vcxproj.filters
src/Updater/Updater.vcxproj.filters

XAML Islands 中 TeachingTip 的弹出动画存在 bug，弹出前有一瞬间完全显示出来。这个 bug 只会在第一次弹出时出现，而且 UWP 和 WinUI 3 都不存在。
为了修复它，弹出前手动将弹窗隐藏，播放弹出动画时再恢复。

修复消息弹出动画错误

---

src/Magpie.Core/Renderer.cpp

使用和 OBS 同样的方法提高 GPU 优先级，某些情况下这可以提高流畅度。有几点需要注意：
1. 我们始终使用“高”优先级。一方面“实时”优先级会造成系统不稳定：OBS 在硬件加速 GPU 调度 (HAGS) 打开时使用“高”优先级否则使用“实时”优先级，[但实际上即使没有打开 HAGS，“实时”优先级也会造成问题](https://github.com/LizardByte/Sunshine/blob/9c08c75a44097a5a5c866d70ccf0c8c080257a0c/src/platform/windows/display_base.cpp#L662)。另一方面我不想让过于激进的优化影响到源窗口的流畅度。
2. [OBS 还使用 IDXGIDevice::SetGPUThreadPriority 提高优先级](https://github.com/obsproject/obs-studio/blob/16cb051a57bb357fe866252c1360ce2c38e2deec/libobs-d3d11/d3d11-subsystem.cpp#L437)。这个接口一般被认为无用，但 OBS 传了一个未记录的值，[似乎真的有用](https://zhuanlan.zhihu.com/p/22604757356)。我尝试传入相同的值但接口返回 0x8876086A (D3DERR_NOTAVAILABLE)，顺带一提我这里 OBS 的调用也会失败，证明这不是专为 OBS 开的后门。

提高 GPU 优先级

---

src/Magpie/AppSettings.cpp

Close #1136 
[KB5055627](https://support.microsoft.com/en-us/topic/april-25-2025-kb5055627-os-build-26100-3915-preview-9324a361-965a-4496-8fd8-ba8a9de9fc38) 后 Win+Shift+A 被 Recall 占用，导致快捷键注册失败。这个 PR 将默认快捷键组合中的 Win 键改为 Alt 键，现在默认快捷键如下：
全屏模式缩放：Alt+Shift+A
窗口模式缩放：Alt+Shift+Q
工具栏状态切换：Alt+Shift+D
新的默认快捷键只有第一次打开 Magpie 时才生效，如果已经有设置文件则不会做更改。

默认快捷键的 Win 改为 Alt 以避免和系统快捷键冲突

---

src/Magpie/Resources.language-en-US.resw
src/Magpie/Resources.language-zh-Hans.resw
src/Magpie/RootPage.cpp
src/Magpie/RootPage.h
src/Magpie/RootPage.xaml

支持填入窗口标题和进程名（非打包应用）/应用名（打包应用），如果标题比进程名更准确，这可以减少键入。

扩展新建配置弹窗中名称文本框右键菜单功能

---

src/Magpie/EffectParametersViewModel.cpp
src/Magpie/EffectParametersViewModel.h
src/Magpie/ScalingModeEffectItem.cpp
src/Magpie/ScalingModeEffectItem.h
src/Magpie/ScalingModeItem.cpp
src/Magpie/ScalingModeItem.h

Close #1154
又一个 WinUI 的 bug，删除缩放模式后 ScalingModeItem 不会立刻析构，而且可能会尝试更新绑定导致崩溃。这个 PR 使 ScalingModeItem、ScalingModeEffectItem 和 EffectParametersViewModel 被删除后仍处于合法的状态，不会因为调用其中的方法而崩溃。这个 bug 似乎在 CPU 较弱时更常见。
缩放模式页面过于复杂，以后会重新设计。

修复删除缩放模式时崩溃

---

src/Magpie/AppSettings.cpp
src/Magpie/FileDialogHelper.cpp
src/Magpie/Profile.h
src/Magpie/ProfileViewModel.cpp

Close #1158
选择 exe 的快捷方式时 IFileOpenDialog 默认会提取出路径并忽略参数，现在使用 FOS_NODEREFERENCELINKS 选项使 IFileDialog 直接返回 lnk。
当快捷方式包含参数时，Magpie 的启动参数选项就无效了。虽然可以在 UI 中给出提示，但我们不是很想实现，如果用快捷方式作为启动器，用户应该知道自己在做什么。

修复选择快捷方式作为启动器时丢失参数

---

src/Magpie.Core/AdaptivePresenter.h
src/Magpie.Core/CompSwapchainPresenter.h
src/Magpie.Core/ScalingOptions.cpp
src/Magpie.Core/ScalingRuntime.cpp
src/Magpie.Core/ScalingWindow.cpp
src/Magpie.Core/ScalingWindow.h
src/Magpie.Core/SrcTracker.cpp
src/Magpie.Core/include/ScalingOptions.h
src/Magpie/AppSettings.cpp
src/Magpie/AppSettings.h
src/Magpie/HomePage.xaml
src/Magpie/HomeViewModel.cpp
src/Magpie/HomeViewModel.h
src/Magpie/HomeViewModel.idl
src/Magpie/MainWindow.h
src/Magpie/ProfilePage.xaml
src/Magpie/ProfileViewModel.cpp
src/Magpie/ProfileViewModel.h
src/Magpie/ProfileViewModel.idl
src/Magpie/Resources.language-en-US.resw
src/Magpie/Resources.language-zh-Hans.resw
src/Magpie/ScalingService.cpp
src/Magpie/Shortcut.h
src/Magpie/ToastPage.cpp

如果缩放窗口置顶会遮挡菜单和弹窗（主要是菜单，我们针对弹窗做了优化），收益却并不高。现在缩放窗口默认不再置顶，提供选项来恢复旧行为。
其他更改：
1. 窗口模式缩放不再支持模拟独占全屏
2. 使用 Desktop Duplication 捕获时禁止窗口模式缩放，旧行为是自动切换到 Graphics Capture
3. 修复消息弹窗会使窗口取消置顶的问题

全屏缩放默认不再置顶

---

src/Magpie.Core/SrcTracker.cpp
src/Magpie.Core/Win32Helper.cpp
src/Magpie/ToastPage.cpp
tools/WindowCase/HungWindow.cpp
tools/WindowCase/HungWindow.h
tools/WindowCase/KirikiriWindow.cpp
tools/WindowCase/KirikiriWindow.h
tools/WindowCase/WindowBase.h
tools/WindowCase/WindowCase.vcxproj
tools/WindowCase/WindowCase.vcxproj.filters
tools/WindowCase/main.cpp
tools/WindowCase/pch.h

Close #1244
不知为何 [IsHungAppWindow](https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-ishungappwindow) 可能会误报。从表现看，游戏可能因为 5 秒没有调用 PeekMessage 被 OS 标记为无响应窗口，但实际上依然处于响应状态，而且没被替换为幽灵窗口。无论原因为何，应避免使用 IsHungAppWindow。
这个 PR 将 IsHungAppWindow 替换为了未记录的函数 [GhostWindowFromHungWindow](https://undoc.airesoft.co.uk/user32.dll/GhostWindowFromHungWindow.php)，检查是否存在幽灵窗口，这也更符合原本的意图。
其他更改：
1. WindowCase 可以模拟无响应窗口
2. 修复了一个消息弹窗检测无响应窗口的 bug

修复有时误报源窗口无响应
