Blinue/Magpie

Magpie/Properties/Resources.ru-RU.resx

Added new resx. localization file

---

README.md

对于热键修改，增加一些基础的必要说明，减少萌新的困惑
To fix https://github.com/Blinue/Magpie/issues/99

docs: 增加热键修改相关注意点

---

Magpie/App.config
Magpie/MainWindow.xaml.cs
Magpie/Options/ApplicationOptionsPage.xaml
Magpie/Properties/Resources.Designer.cs
Magpie/Properties/Resources.resx
Magpie/Properties/Settings.Designer.cs
Magpie/Properties/Settings.settings

现在关闭窗口就等于直接关掉了，只有最小化时才会变成托盘，感觉这样不太符合操作直觉，所以想是不是可以在关闭时直接进托盘，彻底退出的话通过托盘退出

feat: minimize when closing window 关闭窗口时最小化到托盘

---

Effects/FSR_RCAS.hlsl

source: https://github.com/GPUOpen-Effects/FidelityFX-FSR/commit/a21ffb8f6c13233ba336352bdff293894c706575
疑虑：原patch有三处同样的修改，但magpie的effects中只有一处，不知是否精简所致。
本地测试没看出什么区别。

feat: FSR update to 1.0.2

---

Effects/Bicubic.hlsl
Effects/Bicubic_Lite.hlsl
Effects/Effects.vcxproj
Effects/Effects.vcxproj.filters
Magpie/Resources/BuiltInScaleModels.json

feat: Mitchell → Bicubic

---

Effects/Bicubic.hlsl
Effects/Bicubic_Lite.hlsl
docs/自定义缩放配置.md

fix: bicubic default

---

Effects/LCAS.hlsl

Sorry to bother you sir, but this should further increase performance and reduce ram usage.
Watch Dogs Legion
LCAS - 1080p to 1440p
DLSS - Balance

LCAS Final update

---

Effects/LCAS.hlsl

Should be better than the last edge checker.
If not, please tell me.

Change edge checker method

---

Effects/LCAS.hlsl

Should be slightly to no bad impact.

Minimize LCAS.hlsl a bit

---

README.md
README_EN.md

我向一些美国玩家推荐了Magpie，但他们读不懂中文README。我翻译了一个英文版的。

added README in English

---

Effects/SMAA.hlsli

chore: fix typo in SMAA.hlsli

---

Effects/CRT_Geom.hlsl

Fix cause of image retention (burn in) #415

Update CRT_Geom.hlsl Re: CRT-Geom Causing Image Retention on ips displays

---

CONTRIBUTING_EN.md
README_EN.md
docs/FAQ_EN.md

Improved the translations on:
- README_EN.md,
- CONTRIBUTING_EN.md,
- docs/FAQ.md.

Translation improvements

---

Effects/Deband.hlsl
Effects/Effects.vcxproj
Effects/Effects.vcxproj.filters

Based on Haasn's deband shader port from https://github.com/haasn/gentoo-conf/blob/xor/home/nand/.mpv/shaders/deband.glsl

add deband shader

---

src/Magpie/app.manifest

https://github.com/microsoft/terminal/issues/12452
现在的文字渲染和设置应用相同。
[对比](https://imgsli.com/MTc2MzQz)

Win11 中启用 Segoe UI Variable

---

src/Magpie.App/Resources.language-en-US.resw
src/Magpie.App/Resources.language-zh-Hans.resw

为快捷键选项添加描述

---

src/Effects/Deband.hlsl
src/Effects/ImageAdjustment.hlsl

Fix effect unable to compile when  'Make effect parameters inline' option is enabled.
#676

Fix effect shader compile error

---

src/Magpie.App/LocalizationService.cpp
src/Magpie.App/Magpie.App.vcxproj
src/Magpie.App/Magpie.App.vcxproj.filters
src/Magpie.App/Resources.language-vi.resw
src/Magpie.Core/OverlayDrawer.cpp

I couldn't submit via Weblate as, at the time of this PR anyway, it has a merge conflict.
Added translations for Vietnamese.

feat: Vietnamese Localizations

---

.conan/.gitignore
.conan/Directory.Build.props
.github/workflows/build.yml
.gitignore
docs/Compilation guide.md
docs/编译指南.md
src/Magpie.App/conanfile.txt
src/Magpie.Core/conanfile.txt
src/Magpie/conanfile.txt
src/Solution.props
src/_ConanDeps/_ConanDeps.vcxproj
src/_ConanDeps/build_conan_deps.py
src/_ConanDeps/conanprofile.txt

generator `visual_studio` 已被废弃，我们应切换到 `MSBuildDeps`，后者的主要优势在于能自动根据当前配置切换环境，无需我们自己处理了。

迁移到 Conan v2

---

src/Magpie.Core/CursorManager.cpp

确定一个窗口是否对鼠标透明需要考虑数个因素：
1. 窗口可见
2. 鼠标位于窗口内
3. 窗口没有被[冻结](https://devblogs.microsoft.com/oldnewthing/20200302-00/?p=103507)
4. 窗口没有 WS_EX_TRANSPARENT 样式
5. 如果窗口是分层窗口，使用 ChildWindowFromPointEx 判断该点是否透明，似乎没有公开的 API 能检测分层窗口是否透明
6. 如果窗口使用 SetWindowRgn 自定义形状，使用 PtInRegion 判断该点是否透明
注意事项：
1. 无需考虑 HTTRANSPARENT，它只能作用于子窗口
2. ChildWindowFromPointEx 也会考虑自定义形状，但只适用于客户区。因此如果鼠标位于客户区，仅使用 ChildWindowFromPointEx 即可；反之如果窗口位于非客户区，则只需考虑自定义形状，因为分层窗口不允许非客户区透明。
3. 如果窗口的 IL 比 Magpie 高，ChildWindowFromPointEx 会失败，因此无法检测分层窗口是否透明。

优化对透明窗口的检测

---

src/Effects/NNEDI3/NNEDI3_nns128_win8x4.hlsl
src/Effects/NNEDI3/NNEDI3_nns128_win8x6.hlsl
src/Effects/NNEDI3/NNEDI3_nns16_win8x4.hlsl
src/Effects/NNEDI3/NNEDI3_nns16_win8x6.hlsl
src/Effects/NNEDI3/NNEDI3_nns256_win8x4.hlsl
src/Effects/NNEDI3/NNEDI3_nns256_win8x6.hlsl
src/Effects/NNEDI3/NNEDI3_nns32_win8x4.hlsl
src/Effects/NNEDI3/NNEDI3_nns32_win8x6.hlsl
src/Effects/NNEDI3/NNEDI3_nns64_win8x4.hlsl
src/Effects/NNEDI3/NNEDI3_nns64_win8x6.hlsl

NNEDI3: fix wrong thread position calculation

---

src/Magpie.App/ScalingService.cpp
src/Shared/Win32Utils.cpp
src/Shared/Win32Utils.h

复用获取窗口进程句柄的代码，以修复 https://github.com/Blinue/Magpie/issues/986

重构获取窗口进程句柄

---

src/Magpie/CandidateWindowItem.h
src/Magpie/ContentDialogHelper.h
src/Magpie/HomePage.cpp
src/Magpie/KeyVisual.h
src/Magpie/MainWindow.cpp
src/Magpie/PageFrame.cpp
src/Magpie/PageFrame.h
src/Magpie/ProfilePage.cpp
src/Magpie/ProfilePage.h
src/Magpie/ProfileViewModel.h
src/Magpie/RootPage.cpp
src/Magpie/ScalingModesPage.cpp
src/Magpie/ScalingModesPage.h
src/Magpie/SettingsCard.h
src/Magpie/SettingsExpander.Resource.xaml
src/Magpie/SettingsExpander.cpp
src/Magpie/SettingsExpander.h
src/Magpie/ShortcutControl.h
src/Magpie/SimpleStackPanel.cpp
src/Magpie/SimpleStackPanel.h
src/Magpie/TextBlockHelper.h
src/Magpie/TitlebarControl.cpp
src/Magpie/WrapPanel.cpp
src/Magpie/WrapPanel.h
src/Magpie/XamlHelper.cpp
src/Magpie/XamlHelper.h
src/Magpie/XamlWindow.h
src/Magpie/pch.h

UWP 自带这个功能，不知道是怎么做到的。我们针对每个加载后显示动画的控件都定制了方案，包括 ToggleSwitch、TitlebarControl 和 SettingsExpander。

刚显示窗口时跳过动画

---

src/Magpie/HomeViewModel.cpp
src/Magpie/NotifyIconService.cpp

Close #524 
由于 Magpie.App 和 Magpie 合并，实现这个功能简单很多。如果倒计时有提示更好，但实现起来很麻烦。

通知区域图标菜单支持定时缩放

---

docs/Performance optimization.md
docs/性能优化建议.md

https://github.com/Blinue/Magpie/discussions/1101
"性能优化建议.md" https://translate.google.com

Detailed performance tips for 24H2 and Nvidia users

---

src/Magpie/ScalingService.cpp

Close #1148
有些游戏刚启动时将窗口创建在屏幕外，初始化完成后再移到屏幕内。如果窗口不在任何屏幕上，缩放将失败，我们应等初始化完成再缩放。

不在任何屏幕上的窗口不检查自动缩放
